Updated scripts. Added `enable-plugin` and `disable-plugin` for plugin management. Updates `clojupyter`, `install` and `list` scripts.

diff --git a/bin/clojupyter b/bin/clojupyter
--- a/bin/clojupyter
+++ b/bin/clojupyter
@@ -1,32 +1,21 @@
 #!/bin/env bash
 
-version() {
-    sed '/:version/ s/^.*"\(.\+\)".*$/\1/g' resources/clojupyter/assets/version.edn
-}
+which lein &>/dev/null && exec=lein
+which clojure &>/dev/null && exec=clojure
 
-install() {
-    echo Installing
-}
+[[ -z $exec ]] && { echo "Can't find lein or clojure on PATH." >&2; exit 2; }
 
-uninstall() {
-    echo Uninstalling
-}
+case $exec in
+    lein)
+    CLASSPATH=$(lein classpath 2>/dev/null)
+    ;;
+    clojure)
+    for path in $(clojure -Spath | sed 's/:/\n/g'); do
+        CLASSPATH+=$(realpath $path):;
+    done
+    ;;
+esac
 
-list () {
-    echo Installed kernels:
-}
-help() {
-    echo "Clojupyter $(version)"
-    echo
-    echo "Available Commands:"
-    echo
-    echo "  - help command* | --help | -h"
-    echo "  - install opts*"
-    echo "  - uninstall opts*"
-    echo "  - list opts* filt*"
-    echo "  - version"
-}
+export CLASSPATH
 
-([[ $# == 0 ]] || [[ $1 == --help ]] || [[ $1 == -h ]]) && { help; exit 0; }
-
-$@
+jupyter $@
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,7 +1,5 @@
 #!/bin/env bash
 
-## TODO: Print errors to stderr
-
 ########################################################################################
 #  DEFAULTS
 ########################################################################################
@@ -56,6 +54,7 @@ while [[ $# -gt 0 ]]; do
         shift
         shift
         ;;
+        ## Missing fail condition for unknown arguments
     esac
 done
 
@@ -86,7 +85,8 @@ fi
 # INSTALLING
 #########################################################################################
 
-mkdir $INSTALLDIR/$IDENT 2>/dev/null
+echo Installing $IDENT to $INSTALLDIR >&2
+mkdir -p $INSTALLDIR/$IDENT/plugins 2>/dev/null
 cp $JAR $INSTALLDIR/$IDENT/clojupyter-standalone.jar &&\
 cp resources/clojupyter/assets/logo-64x64.png $INSTALLDIR/$IDENT/. &&\
 
